# Generated by Django 5.2.7 on 2025-10-18 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('landlord', 'Landlord'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='Username must be at least 3 characters long.'), django.core.validators.RegexValidator(code='invalid_username', message='Username can only contain letters, numbers, periods (.), underscores (_).', regex='^[a-zA-Z0-9._]+$')]),
        ),
    ]
