# Generated by Django 5.2.7 on 2025-10-17 15:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommateGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('address', models.TextField()),
                ('university', models.CharField(max_length=255)),
                ('number_of_members', models.IntegerField()),
                ('cost_per_member', models.DecimalField(decimal_places=2, help_text='Cost/each', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RoommatePost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_budget', models.CharField(max_length=255)),
                ('preferred_type', models.CharField(blank=True, help_text='apartment-studio', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('female_only', models.BooleanField(default=False)),
                ('university', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
