# Generated by Django 5.2.7 on 2025-11-04 15:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommatePost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_budget', models.DecimalField(decimal_places=2, help_text='Maximum monthly budget per person', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('preferred_type', models.CharField(blank=True, choices=[('APARTMENT', 'Apartment'), ('STUDIO', 'Studio'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('female_only', models.BooleanField(default=False)),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoommateRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoommateGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('max_members', models.IntegerField(default=4, help_text='Maximum number of members allowed', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)])),
                ('cost_per_member', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated cost per member (e.g., listing price / members)', max_digits=10, null=True)),
                ('female_only', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open for Joins'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('conversation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
