# Generated by Django 5.2.7 on 2025-11-04 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_owner'),
        ('roommates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roommategroup',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_roommate_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roommategroup',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.listing'),
        ),
        migrations.AddField(
            model_name='roommategroup',
            name='members',
            field=models.ManyToManyField(limit_choices_to={'role__in': ['student', 'other']}, related_name='roommate_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roommatepost',
            name='author',
            field=models.ForeignKey(default=1, limit_choices_to={'role__in': ['student', 'other']}, on_delete=django.db.models.deletion.CASCADE, related_name='roommate_posts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roommaterequest',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommates.roommatepost'),
        ),
        migrations.AddField(
            model_name='roommaterequest',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_roommate_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roommaterequest',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_roommate_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='roommaterequest',
            unique_together={('sender', 'receiver')},
        ),
    ]
