# Generated by Django 5.2.7 on 2025-11-03 16:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_rename_deed_number_listing_deed_number_and_more'),
        ('messaging', '0002_remove_message_recipient_remove_message_timestamp_and_more'),
        ('roommates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roommategroup',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='roommatepost',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='roommategroup',
            name='number_of_members',
        ),
        migrations.AddField(
            model_name='roommategroup',
            name='conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='roommategroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='roommategroup',
            name='female_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roommategroup',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_roommate_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roommategroup',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.listing'),
        ),
        migrations.AddField(
            model_name='roommategroup',
            name='max_members',
            field=models.IntegerField(default=4, help_text='Maximum number of members allowed', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='roommategroup',
            name='members',
            field=models.ManyToManyField(limit_choices_to={'role__in': ['student', 'other']}, related_name='roommate_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roommategroup',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open for Joins'), ('CLOSED', 'Closed')], default='OPEN', max_length=10),
        ),
        migrations.AddField(
            model_name='roommategroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='roommatepost',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roommatepost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='roommategroup',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roommategroup',
            name='cost_per_member',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated cost per member (e.g., listing price / members)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='roommategroup',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roommatepost',
            name='author',
            field=models.ForeignKey(limit_choices_to={'role__in': ['student', 'other']}, on_delete=django.db.models.deletion.CASCADE, related_name='roommate_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roommatepost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='roommatepost',
            name='max_budget',
            field=models.DecimalField(decimal_places=2, help_text='Maximum monthly budget per person', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='roommatepost',
            name='preferred_type',
            field=models.CharField(blank=True, choices=[('APARTMENT', 'Apartment'), ('STUDIO', 'Studio'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roommatepost',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='RoommateRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommates.roommatepost')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_roommate_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_roommate_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
