# Generated by Django 5.2.7 on 2025-11-04 15:50

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_type', models.CharField(choices=[('National_ID', 'National ID'), ('Resident_ID', 'Resident ID')], max_length=25)),
                ('owner_identification_id', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_ID_number', message='ID number must be 10 digits only!', regex='^\\d{10}$')])),
                ('deed_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_deed_number', message='Deed number must be 10 digits only!', regex='^\\d{10}$')])),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Monthly Price', max_digits=10)),
                ('type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('STUDIO', 'Studio'), ('OTHER', 'Other')], max_length=10)),
                ('female_only', models.BooleanField(default=False)),
                ('roommates_allowed', models.BooleanField(default=False)),
                ('student_discount', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('AVAILABLE', 'Available'), ('DRAFT', 'Draft')], max_length=10)),
                ('district', models.CharField(choices=[('AL_AMAL', 'Al Amal'), ('AL_AQEEQ', 'Al Aqeeq'), ('AL_ARID', 'Al Arid'), ('AL_AWALI', 'Al Awali'), ('AL_AZIZIYAH', 'Al Aziziyah'), ('AL_BADIAH', 'Al Badiah'), ('AL_BAYAN', 'Al Bayan'), ('AL_DAR_AL_BAIDA', 'Al Dar Al Baida'), ('AL_DUBAT', 'Al Dubat'), ('AL_FAIHA', 'Al Faiha'), ('AL_FARUQ', 'Al Faruq'), ('AL_GHANAMIYAH', 'Al Ghanamiyah'), ('AL_HAIR', 'Al Hair'), ('AL_HAMRA', 'Al Hamra'), ('AL_HAZM', 'Al Hazm'), ('AL_IZDIHAR', 'Al Izdihar'), ('AL_JANADRIYAH', 'Al Janadriyah'), ('AL_JARADIYA', 'Al Jaradiya'), ('AL_KHALEEJ', 'Al Khaleej'), ('AL_KHALIDIYAH', 'Al Khalidiyah'), ('AL_MAATHER', 'Al Maather'), ('AL_MAGHARZAT', 'Al Magharzat'), ('AL_MAHDIYAH', 'Al Mahdiyah'), ('AL_MALAZ', 'Al Malaz'), ('AL_MALQA', 'Al Malqa'), ('AL_MANSURIYAH', 'Al Mansuriyah'), ('AL_MARWAH', 'Al Marwah'), ('AL_MASHRIQ', 'Al Mashriq'), ('AL_MUAIZILAH', 'Al Muaizilah'), ('AL_MUNSIYAH', 'Al Munsiyah'), ('AL_MURQAB', 'Al Murqab'), ('AL_MURSALAT', 'Al Mursalat'), ('AL_MURUJ', 'Al Muruj'), ('AL_MUSEEF', 'Al Museef'), ('AL_MUSFAH', 'Al Musfah'), ('AL_NADA', 'Al Nada'), ('AL_NAFL', 'Al Nafl'), ('AL_NAHDAH', 'Al Nahdah'), ('AL_NAKHEEL', 'Al Nakheel'), ('AL_NARJIS', 'Al Narjis'), ('AL_NASEEM_AL_GHARBI', 'Al Naseem Al Gharbi'), ('AL_NASEEM_AL_SHARQI', 'Al Naseem Al Sharqi'), ('AL_NAZEEM', 'Al Nazeem'), ('AL_NUZHAH', 'Al Nuzhah'), ('AL_OLAYA', 'Al Olaya'), ('AL_OUD', 'Al Oud'), ('AL_QADISIYAH', 'Al Qadisiyah'), ('AL_QAIRAWAN', 'Al Qairawan'), ('AL_RABEE', 'Al Rabee'), ('AL_RABWAH', 'Al Rabwah'), ('AL_RAHMANIYAH', 'Al Rahmaniyah'), ('AL_RAWABI', 'Al Rawabi'), ('AL_RAWDAH', 'Al Rawdah'), ('AL_RAYYAN', 'Al Rayyan'), ('AL_RIMAL', 'Al Rimal'), ('AL_RIYADH', 'Al Riyadh'), ('AL_SAADAH', 'Al Saadah'), ('AL_SAFA', 'Al Safa'), ('AL_SAHAB', 'Al Sahab'), ('AL_SAHAFAH', 'Al Sahafah'), ('AL_SHIFA', 'Al Shifa'), ('AL_SHUALA', 'Al Shuala'), ('AL_SHUHADA', 'Al Shuhada'), ('AL_SIDRAH', 'Al Sidrah'), ('AL_SULIMANIYAH', 'Al Sulimaniyah'), ('AL_SUWAIDI', 'Al Suwaidi'), ('AL_SUWAIDI_AL_GHARBI', 'Al Suwaidi Al Gharbi'), ('AL_TAAWUN', 'Al Taawun'), ('AL_ULA', 'Al Ula'), ('AL_URAIJA', 'Al Uraija'), ('AL_URAIJA_AL_GHARBIYAH', 'Al Uraija Al Gharbiyah'), ('AL_URAIJA_AL_WUSTA', 'Al Uraija Al Wusta'), ('AL_WADI', 'Al Wadi'), ('AL_WISAM', 'Al Wisam'), ('AL_WURUD', 'Al Wurud'), ('AL_YARMUK', 'Al Yarmuk'), ('AL_YASMEEN', 'Al Yasmeen'), ('AL_ZAHER', 'Al Zaher'), ('AL_ZAHRA', 'Al Zahra'), ('AREED', 'Areed'), ('BADR', 'Badr'), ('BANBAN', 'Banban'), ('DAHIYAT_NAMAR', 'Dahiyat Namar'), ('DHAHRAT_LABAN', 'Dhahrat Laban'), ('DIRAB', 'Dirab'), ('GHIRNATAH', 'Ghirnatah'), ('GHUBAIRA', 'Ghubaira'), ('HITTIN', 'Hittin'), ('IRQAH', 'Irqah'), ('ISHBILIYA', 'Ishbiliya'), ('JARIR', 'Jarir'), ('KING_ABDULLAH', 'King Abdullah'), ('KING_FAHD', 'King Fahd'), ('KING_FAISAL', 'King Faisal'), ('KING_KHALID_AIRPORT', 'King Khalid International Airport'), ('LABAN', 'Laban'), ('MANFUHAH', 'Manfuhah'), ('MUKHATAT_AL_KHAIR', 'Mukhatat Al Khair'), ('NAMAR', 'Namar'), ('QURTUBAH', 'Qurtubah'), ('SHUBRA', 'Shubra'), ('SIDRAH', 'Sidrah'), ('SULTANAH', 'Sultanah'), ('TAYBAH', 'Taybah'), ('TUWAIQ', 'Tuwaiq'), ('UHUD', 'Uhud'), ('UKAZ', 'Ukaz'), ('ULAYSHAH', 'Ulayshah')], help_text='Select the district/neighborhood', max_length=100)),
                ('location_link', models.URLField(max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('can_create_listing', 'Can create a listing'), ('can_view_listing_creation', 'Can view listing creation')],
            },
        ),
    ]
