# Generated by Django 5.2.7 on 2025-10-17 15:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Monthly Price', max_digits=10)),
                ('type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('STUDIO', 'Studio')], max_length=10)),
                ('female_only', models.BooleanField(default=False)),
                ('roommates_allowed', models.BooleanField(default=False)),
                ('student_discount', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('AVAILABLE', 'Available')], max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_link', models.URLField(max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
