# Generated by Django 5.2.7 on 2025-11-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='area',
            field=models.PositiveIntegerField(blank=True, help_text='Area in square meters', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
