# Generated by Django 5.2.7 on 2025-10-19 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_options_listing_owner_national_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='owner_national_id',
            new_name='owner_identification_id',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='address',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='longitude',
        ),
        migrations.AddField(
            model_name='listing',
            name='deed_Number',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_deed_number', message='Deed number must be 10 digits only!', regex='^\\d{10}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='district',
            field=models.CharField(choices=[('UHUD', 'Uhud'), ('ISHBILIYA', 'Ishbiliya'), ('AL_IZDIHAR', 'Al Izdihar'), ('AL_BADIAH', 'Al Badiah'), ('AL_TAAWUN', 'Al Taawun'), ('AL_JARADIYA', 'Al Jaradiya'), ('AL_JANADRIYAH', 'Al Janadriyah'), ('AL_HAIR', 'Al Hair'), ('AL_HAZM', 'Al Hazm'), ('AL_HAMRA', 'Al Hamra'), ('AL_KHALIDIYAH', 'Al Khalidiyah'), ('AL_KHALEEJ', 'Al Khaleej'), ('AL_DAR_AL_BAIDA', 'Al Dar Al Baida'), ('AL_RABWAH', 'Al Rabwah'), ('AL_RABEE', 'Al Rabee'), ('AL_RAHMANIYAH', 'Al Rahmaniyah'), ('AL_RIMAL', 'Al Rimal'), ('AL_RAWABI', 'Al Rawabi'), ('AL_RAWDAH', 'Al Rawdah'), ('AL_RIYADH', 'Al Riyadh'), ('AL_RAYYAN', 'Al Rayyan'), ('AL_ZAHER', 'Al Zaher'), ('AL_ZAHRA', 'Al Zahra'), ('AL_SAHAB', 'Al Sahab'), ('AL_SAADAH', 'Al Saadah'), ('AL_SULIMANIYAH', 'Al Sulimaniyah'), ('AL_SUWAIDI', 'Al Suwaidi'), ('AL_SUWAIDI_AL_GHARBI', 'Al Suwaidi Al Gharbi'), ('AL_SHUALA', 'Al Shuala'), ('AL_SHIFA', 'Al Shifa'), ('AL_SHUHADA', 'Al Shuhada'), ('AL_SAHAFAH', 'Al Sahafah'), ('AL_SAFA', 'Al Safa'), ('AL_DUBAT', 'Al Dubat'), ('AL_ARID', 'Al Arid'), ('AL_URAIJA', 'Al Uraija'), ('AL_URAIJA_AL_GHARBIYAH', 'Al Uraija Al Gharbiyah'), ('AL_URAIJA_AL_WUSTA', 'Al Uraija Al Wusta'), ('AL_AZIZIYAH', 'Al Aziziyah'), ('AL_AQEEQ', 'Al Aqeeq'), ('AL_ULA', 'Al Ula'), ('AL_OLAYA', 'Al Olaya'), ('AL_AMAL', 'Al Amal'), ('AL_AWALI', 'Al Awali'), ('AL_OUD', 'Al Oud'), ('AL_GHANAMIYAH', 'Al Ghanamiyah'), ('AL_FARUQ', 'Al Faruq'), ('AL_FAIHA', 'Al Faiha'), ('AL_QADISIYAH', 'Al Qadisiyah'), ('AL_QAIRAWAN', 'Al Qairawan'), ('AL_MURSALAT', 'Al Mursalat'), ('AL_MURQAB', 'Al Murqab'), ('AL_MARWAH', 'Al Marwah'), ('AL_MURUJ', 'Al Muruj'), ('AL_MASHRIQ', 'Al Mashriq'), ('AL_MUSFAH', 'Al Musfah'), ('AL_MUSEEF', 'Al Museef'), ('AL_MAATHER', 'Al Maather'), ('AL_MUAIZILAH', 'Al Muaizilah'), ('AL_MAGHARZAT', 'Al Magharzat'), ('AL_MALAZ', 'Al Malaz'), ('AL_MALQA', 'Al Malqa'), ('KING_ABDULLAH', 'King Abdullah'), ('KING_FAHD', 'King Fahd'), ('KING_FAISAL', 'King Faisal'), ('AL_MANSURIYAH', 'Al Mansuriyah'), ('AL_MAHDIYAH', 'Al Mahdiyah'), ('AL_MUNSIYAH', 'Al Munsiyah'), ('AL_NAKHEEL', 'Al Nakheel'), ('AL_NADA', 'Al Nada'), ('AL_NARJIS', 'Al Narjis'), ('AL_NUZHAH', 'Al Nuzhah'), ('AL_NASEEM_AL_SHARQI', 'Al Naseem Al Sharqi'), ('AL_NASEEM_AL_GHARBI', 'Al Naseem Al Gharbi'), ('AL_NAZEEM', 'Al Nazeem'), ('AL_NAFL', 'Al Nafl'), ('AL_NAHDAH', 'Al Nahdah'), ('AL_WADI', 'Al Wadi'), ('AL_WURUD', 'Al Wurud'), ('AL_WISAM', 'Al Wisam'), ('AL_YASMEEN', 'Al Yasmeen'), ('AL_YARMUK', 'Al Yarmuk'), ('BADR', 'Badr'), ('BANBAN', 'Banban'), ('JARIR', 'Jarir'), ('HITTIN', 'Hittin'), ('AL_BAYAN', 'Al Bayan'), ('AL_SIDRAH', 'Al Sidrah'), ('DIRAB', 'Dirab'), ('SIDRAH', 'Sidrah'), ('SULTANAH', 'Sultanah'), ('SHUBRA', 'Shubra'), ('DAHIYAT_NAMAR', 'Dahiyat Namar'), ('TUWAIQ', 'Tuwaiq'), ('TAYBAH', 'Taybah'), ('DHAHRAT_LABAN', 'Dhahrat Laban'), ('IRQAH', 'Irqah'), ('AREED', 'Areed'), ('UKAZ', 'Ukaz'), ('ULAYSHAH', 'Ulayshah'), ('GHUBAIRA', 'Ghubaira'), ('GHIRNATAH', 'Ghirnatah'), ('QURTUBAH', 'Qurtubah'), ('LABAN', 'Laban'), ('MUKHATAT_AL_KHAIR', 'Mukhatat Al Khair'), ('KING_KHALID_AIRPORT', 'King Khalid International Airport'), ('MANFUHAH', 'Manfuhah'), ('NAMAR', 'Namar')], default=0, help_text='Select the district/neighborhood', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='id_type',
            field=models.CharField(choices=[('National_ID', 'National ID'), ('Resident_ID', 'Resident ID'), ('Passport', 'Passport Number'), ('license_No', 'License Number')], default=0, max_length=25),
            preserve_default=False,
        ),
    ]
