# Generated by Django 5.2.7 on 2025-11-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listingimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingimage',
            options={'ordering': ['-is_primary', 'id']},
        ),
        migrations.RemoveField(
            model_name='listingimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(default=1, upload_to='listings/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
