# Districts list from Kaggle Riyadh Real Estate dataset
# Source column: District
# Original Arabic names - ready for translation

districts_AR = [
    ('حي_احد', 'حي احد'),
    ('حي_اشبيلية', 'حي اشبيلية'),
    ('حي_الازدهار', 'حي الازدهار'),
    ('حي_البديعة', 'حي البديعة'),
    ('حي_التعاون', 'حي التعاون'),
    ('حي_الجرادية', 'حي الجرادية'),
    ('حي_الجنادرية', 'حي الجنادرية'),
    ('حي_الحائر', 'حي الحائر'),
    ('حي_الحزم', 'حي الحزم'),
    ('حي_الحمراء', 'حي الحمراء'),
    ('حي_الخالدية', 'حي الخالدية'),
    ('حي_الخليج', 'حي الخليج'),
    ('حي_الدار_البيضاء', 'حي الدار البيضاء'),
    ('حي_الربوة', 'حي الربوة'),
    ('حي_الربيع', 'حي الربيع'),
    ('حي_الرحمانية', 'حي الرحمانية'),
    ('حي_الرمال', 'حي الرمال'),
    ('حي_الروابي', 'حي الروابي'),
    ('حي_الروضة', 'حي الروضة'),
    ('حي_الرياض', 'حي الرياض'),
    ('حي_الريان', 'حي الريان'),
    ('حي_الزاهر', 'حي الزاهر'),
    ('حي_الزهرة', 'حي الزهرة'),
    ('حي_السحاب', 'حي السحاب'),
    ('حي_السعادة', 'حي السعادة'),
    ('حي_السليمانية', 'حي السليمانية'),
    ('حي_السويدي', 'حي السويدي'),
    ('حي_السويدي_الغربي', 'حي السويدي الغربي'),
    ('حي_الشعلة', 'حي الشعلة'),
    ('حي_الشفا', 'حي الشفا'),
    ('حي_الشهداء', 'حي الشهداء'),
    ('حي_الصحافة', 'حي الصحافة'),
    ('حي_الصفا', 'حي الصفا'),
    ('حي_الضباط', 'حي الضباط'),
    ('حي_العارض', 'حي العارض'),
    ('حي_العريجاء', 'حي العريجاء'),
    ('حي_العريجاء_الغربية', 'حي العريجاء الغربية'),
    ('حي_العريجاء_الوسطى', 'حي العريجاء الوسطى'),
    ('حي_العزيزية', 'حي العزيزية'),
    ('حي_العقيق', 'حي العقيق'),
    ('حي_العلا', 'حي العلا'),
    ('حي_العليا', 'حي العليا'),
    ('حي_العمل', 'حي العمل'),
    ('حي_العوالي', 'حي العوالي'),
    ('حي_العود', 'حي العود'),
    ('حي_الغنامية', 'حي الغنامية'),
    ('حي_الفاروق', 'حي الفاروق'),
    ('حي_الفيحاء', 'حي الفيحاء'),
    ('حي_القادسية', 'حي القادسية'),
    ('حي_القيروان', 'حي القيروان'),
    ('حي_المرسلات', 'حي المرسلات'),
    ('حي_المرقب', 'حي المرقب'),
    ('حي_المروة', 'حي المروة'),
    ('حي_المروج', 'حي المروج'),
    ('حي_المشرق', 'حي المشرق'),
    ('حي_المصفاة', 'حي المصفاة'),
    ('حي_المصيف', 'حي المصيف'),
    ('حي_المعذر', 'حي المعذر'),
    ('حي_المعيزلة', 'حي المعيزلة'),
    ('حي_المغرزات', 'حي المغرزات'),
    ('حي_الملز', 'حي الملز'),
    ('حي_الملقا', 'حي الملقا'),
    ('حي_الملك_عبدالله', 'حي الملك عبدالله'),
    ('حي_الملك_فهد', 'حي الملك فهد'),
    ('حي_الملك_فيصل', 'حي الملك فيصل'),
    ('حي_المنصورية', 'حي المنصورية'),
    ('حي_المهدية', 'حي المهدية'),
    ('حي_المونسية', 'حي المونسية'),
    ('حي_النخيل', 'حي النخيل'),
    ('حي_الندى', 'حي الندى'),
    ('حي_النرجس', 'حي النرجس'),
    ('حي_النزهة', 'حي النزهة'),
    ('حي_النسيم_الشرقي', 'حي النسيم الشرقي'),
    ('حي_النسيم_الغربي', 'حي النسيم الغربي'),
    ('حي_النظيم', 'حي النظيم'),
    ('حي_النفل', 'حي النفل'),
    ('حي_النهضة', 'حي النهضة'),
    ('حي_الوادي', 'حي الوادي'),
    ('حي_الورود', 'حي الورود'),
    ('حي_الوسام', 'حي الوسام'),
    ('حي_الياسمين', 'حي الياسمين'),
    ('حي_اليرموك', 'حي اليرموك'),
    ('حي_بدر', 'حي بدر'),
    ('حي_بنبان', 'حي بنبان'),
    ('حي_جرير', 'حي جرير'),
    ('حي_حطين', 'حي حطين'),
    ('حي_حي_البيان', 'حي حي البيان'),
    ('حي_حي_السدره', 'حي حي السدره'),
    ('حي_ديراب', 'حي ديراب'),
    ('حي_سدرة', 'حي سدرة'),
    ('حي_سلطانة', 'حي سلطانة'),
    ('حي_شبرا', 'حي شبرا'),
    ('حي_ضاحية_نمار', 'حي ضاحية نمار'),
    ('حي_طويق', 'حي طويق'),
    ('حي_طيبة', 'حي طيبة'),
    ('حي_ظهرة_لبن', 'حي ظهرة لبن'),
    ('حي_عرقة', 'حي عرقة'),
    ('حي_عريض', 'حي عريض'),
    ('حي_عكاظ', 'حي عكاظ'),
    ('حي_عليشة', 'حي عليشة'),
    ('حي_غبيرة', 'حي غبيرة'),
    ('حي_غرناطة', 'حي غرناطة'),
    ('حي_قرطبة', 'حي قرطبة'),
    ('حي_لبن', 'حي لبن'),
    ('حي_مخطط_الخير', 'حي مخطط الخير'),
    ('حي_مطار_الملك_خالد_الدولي', 'حي مطار الملك خالد الدولي'),
    ('حي_منفوحة', 'حي منفوحة'),
    ('حي_نمار', 'حي نمار'),
]

# Districts list from Kaggle Riyadh Real Estate dataset
# English translated names for Django model

districts = [
    ('UHUD', 'Uhud'),
    ('ISHBILIYA', 'Ishbiliya'),
    ('AL_IZDIHAR', 'Al Izdihar'),
    ('AL_BADIAH', 'Al Badiah'),
    ('AL_TAAWUN', 'Al Taawun'),
    ('AL_JARADIYA', 'Al Jaradiya'),
    ('AL_JANADRIYAH', 'Al Janadriyah'),
    ('AL_HAIR', 'Al Hair'),
    ('AL_HAZM', 'Al Hazm'),
    ('AL_HAMRA', 'Al Hamra'),
    ('AL_KHALIDIYAH', 'Al Khalidiyah'),
    ('AL_KHALEEJ', 'Al Khaleej'),
    ('AL_DAR_AL_BAIDA', 'Al Dar Al Baida'),
    ('AL_RABWAH', 'Al Rabwah'),
    ('AL_RABEE', 'Al Rabee'),
    ('AL_RAHMANIYAH', 'Al Rahmaniyah'),
    ('AL_RIMAL', 'Al Rimal'),
    ('AL_RAWABI', 'Al Rawabi'),
    ('AL_RAWDAH', 'Al Rawdah'),
    ('AL_RIYADH', 'Al Riyadh'),
    ('AL_RAYYAN', 'Al Rayyan'),
    ('AL_ZAHER', 'Al Zaher'),
    ('AL_ZAHRA', 'Al Zahra'),
    ('AL_SAHAB', 'Al Sahab'),
    ('AL_SAADAH', 'Al Saadah'),
    ('AL_SULIMANIYAH', 'Al Sulimaniyah'),
    ('AL_SUWAIDI', 'Al Suwaidi'),
    ('AL_SUWAIDI_AL_GHARBI', 'Al Suwaidi Al Gharbi'),
    ('AL_SHUALA', 'Al Shuala'),
    ('AL_SHIFA', 'Al Shifa'),
    ('AL_SHUHADA', 'Al Shuhada'),
    ('AL_SAHAFAH', 'Al Sahafah'),
    ('AL_SAFA', 'Al Safa'),
    ('AL_DUBAT', 'Al Dubat'),
    ('AL_ARID', 'Al Arid'),
    ('AL_URAIJA', 'Al Uraija'),
    ('AL_URAIJA_AL_GHARBIYAH', 'Al Uraija Al Gharbiyah'),
    ('AL_URAIJA_AL_WUSTA', 'Al Uraija Al Wusta'),
    ('AL_AZIZIYAH', 'Al Aziziyah'),
    ('AL_AQEEQ', 'Al Aqeeq'),
    ('AL_ULA', 'Al Ula'),
    ('AL_OLAYA', 'Al Olaya'),
    ('AL_AMAL', 'Al Amal'),
    ('AL_AWALI', 'Al Awali'),
    ('AL_OUD', 'Al Oud'),
    ('AL_GHANAMIYAH', 'Al Ghanamiyah'),
    ('AL_FARUQ', 'Al Faruq'),
    ('AL_FAIHA', 'Al Faiha'),
    ('AL_QADISIYAH', 'Al Qadisiyah'),
    ('AL_QAIRAWAN', 'Al Qairawan'),
    ('AL_MURSALAT', 'Al Mursalat'),
    ('AL_MURQAB', 'Al Murqab'),
    ('AL_MARWAH', 'Al Marwah'),
    ('AL_MURUJ', 'Al Muruj'),
    ('AL_MASHRIQ', 'Al Mashriq'),
    ('AL_MUSFAH', 'Al Musfah'),
    ('AL_MUSEEF', 'Al Museef'),
    ('AL_MAATHER', 'Al Maather'),
    ('AL_MUAIZILAH', 'Al Muaizilah'),
    ('AL_MAGHARZAT', 'Al Magharzat'),
    ('AL_MALAZ', 'Al Malaz'),
    ('AL_MALQA', 'Al Malqa'),
    ('KING_ABDULLAH', 'King Abdullah'),
    ('KING_FAHD', 'King Fahd'),
    ('KING_FAISAL', 'King Faisal'),
    ('AL_MANSURIYAH', 'Al Mansuriyah'),
    ('AL_MAHDIYAH', 'Al Mahdiyah'),
    ('AL_MUNSIYAH', 'Al Munsiyah'),
    ('AL_NAKHEEL', 'Al Nakheel'),
    ('AL_NADA', 'Al Nada'),
    ('AL_NARJIS', 'Al Narjis'),
    ('AL_NUZHAH', 'Al Nuzhah'),
    ('AL_NASEEM_AL_SHARQI', 'Al Naseem Al Sharqi'),
    ('AL_NASEEM_AL_GHARBI', 'Al Naseem Al Gharbi'),
    ('AL_NAZEEM', 'Al Nazeem'),
    ('AL_NAFL', 'Al Nafl'),
    ('AL_NAHDAH', 'Al Nahdah'),
    ('AL_WADI', 'Al Wadi'),
    ('AL_WURUD', 'Al Wurud'),
    ('AL_WISAM', 'Al Wisam'),
    ('AL_YASMEEN', 'Al Yasmeen'),
    ('AL_YARMUK', 'Al Yarmuk'),
    ('BADR', 'Badr'),
    ('BANBAN', 'Banban'),
    ('JARIR', 'Jarir'),
    ('HITTIN', 'Hittin'),
    ('AL_BAYAN', 'Al Bayan'),
    ('AL_SIDRAH', 'Al Sidrah'),
    ('DIRAB', 'Dirab'),
    ('SIDRAH', 'Sidrah'),
    ('SULTANAH', 'Sultanah'),
    ('SHUBRA', 'Shubra'),
    ('DAHIYAT_NAMAR', 'Dahiyat Namar'),
    ('TUWAIQ', 'Tuwaiq'),
    ('TAYBAH', 'Taybah'),
    ('DHAHRAT_LABAN', 'Dhahrat Laban'),
    ('IRQAH', 'Irqah'),
    ('AREED', 'Areed'),
    ('UKAZ', 'Ukaz'),
    ('ULAYSHAH', 'Ulayshah'),
    ('GHUBAIRA', 'Ghubaira'),
    ('GHIRNATAH', 'Ghirnatah'),
    ('QURTUBAH', 'Qurtubah'),
    ('LABAN', 'Laban'),
    ('MUKHATAT_AL_KHAIR', 'Mukhatat Al Khair'),
    ('KING_KHALID_AIRPORT', 'King Khalid International Airport'),
    ('MANFUHAH', 'Manfuhah'),
    ('NAMAR', 'Namar'),
]